### ISSUE TITLE
Does it supports ES6?

### ISSUE THREAD

**Issue by hemant-learningforever** [rjamesnw/v8dotnet#17]
Does it supports ES6?

**Comment by rjamesnw** [comment]
NodeJS is the underlying technology, so your question should be does NodeJS support ES6, which it does.

**Comment by hemant-learningforever** [comment]
Thanks @rjamesnw . This means i can execute script written in ES6 without any issue using v8.net.
Hope i am clear and correct?

**Comment by rjamesnw** [comment]
Correct - same as I also do with NodeJS, which also uses V8. ;)
