### ISSUE TITLE
v8dotnet not compatible with v8 version 5.x

### ISSUE THREAD

**Issue by Nanonid** [rjamesnw/v8dotnet#2]
Many of the dependencies in v8 have changed and now v8dotnet will not compile.

**Comment by rjamesnw** [comment]
Hi, sorry, the updated code is on CodePlex - I may not have updated this repo yet.

**Comment by rjamesnw** [comment]
This is long overdo, so my apologies. I've been pulled away from the whole project for awhile but I'm back now.  There's been a lot more changes as well (such as moving to gclient, depot tools, and gn). I'm rebuilding the command line tool to make this a bit easier for others to get setup.

**Comment by rjamesnw** [comment]
I've merged the dev code with GitHub, and will use that repo from now on.
