### ISSUE TITLE
Run NodeJS

### ISSUE THREAD

**Issue by snappshare** [rjamesnw/v8dotnet#20]
Hi,
i want to emulate a browser inside of v8.
After some research i found [jsdom](https://github.com/jsdom/jsdom) which implements the things needed to archive this.
My problem is that this script requires node.js.
Is there any way to make this script run on v8 via your wrapper?
I would be really glad to receive some tips for this. Thanks!

**Comment by rjamesnw** [comment]
NodeJS is a wrapper around V8. It introduces or extends the V8 JavaScript environment. V8.Net is also a wrapper, but only exposes the raw basic environment. It does not add all the bells and whistles that NodeJS does. To run a NodeJS script in V8.Net, or ANY V8-wrapper, you would have to emulate the NodeJS environment yourself. That’s means your virtual browser script would have to also be emulated by another NodeJS emulator, which I doubt is a good design choice.
