### ISSUE TITLE
Changing Context

### ISSUE THREAD

**Issue by Zeon-4** [rjamesnw/v8dotnet#22]
How to make function like require()?
I tested and send issue: 
#21

**Comment by Zeon-4** [comment]
I have 'test' varible, but when require how to isolate?

**Comment by Zeon-4** [comment]
I have js code:
```
var i = 12;
var test = require("test");
print(test.a);
print(i);
```
I have file test.js:
```
var i = 20;
exports.a = 13;
```
Prints:
```
13
20
```
How to isolate global varibles from change

**Comment by rjamesnw** [comment]
I think you can share values between contexts within the same isolate.  You would have to create another context which has its own fresh global object, then switch the context when you execute the code to be isolated.  In the new context, I would wrap your code in a function, then pass it values as you need to when calling, or copy over values from the main context to the new context. You may also consider calling `Object.freeze` on the new context to prevent it from being changed, while allowing the main context to remain mutable.

**Comment by Zeon-4** [comment]
I tried changing context:
```
V8Engine engine = new V8Engine();
        Context contx = engine.CreateContext();
        engine.RegisterType<Console>(null,true,ScriptMemberSecurity.Locked);
        engine.DynamicGlobalObject.console = new Console("Test");
        engine.Execute("var i = 0; console.log(i);","Test",true,0,true);
        engine.SetContext(contx);
        engine.Execute("console.log(i);");
```
But have error:
```
InvalidOperationException: The handle is locked and cannot be disposed. Locked handles are either the global object, or belong to 'V8NativeObject' objects, which are responsible for disposing them under controlled conditions.
V8.Net.InternalHandle._Dispose (System.Boolean ignoreErrors) (at <0db0c1d97db54bf181ab63a974eaffda>:0)
V8.Net.InternalHandle.Dispose () (at <0db0c1d97db54bf181ab63a974eaffda>:0)
V8.Net.InternalHandle._Set (V8.Net.HandleProxy* hp) (at <0db0c1d97db54bf181ab63a974eaffda>:0)
V8.Net.InternalHandle.Set (V8.Net.InternalHandle h) (at <0db0c1d97db54bf181ab63a974eaffda>:0)
V8.Net.V8Engine.SetContext (V8.Net.Context context) (at <0db0c1d97db54bf181ab63a974eaffda>:0)
```

**Comment by rjamesnw** [comment]
Thanks, I’ll look into this. It may be old logic protecting it back when I only allowed a single context. To be honest I’ve never had need to swap contexts, as most people don’t either, so I need to review it a bit more.

**Comment by Zeon-4** [comment]
OK, I rename issue

**Comment by rjamesnw** [comment]
The new release has this fixed.
