### ISSUE TITLE
Callback problem. GC clear InternalHandle

### ISSUE THREAD

**Issue by Zeon-4** [rjamesnw/v8dotnet#23]
I maked function with callback 
`Add(string event_name, string func_name, InternalHandle callback)`
I call callback after execution but, GC clear InternalHandle.
It possible clone or other way to call callback?
Thanks!

**Comment by rjamesnw** [comment]
Try this: `callback.KeepTrack()`

**Comment by rjamesnw** [comment]
For the record, it’s not the GC. All internal handles passed to callbacks are disposed by the wrapper, unless you explicitly tell the system to let the GC Track it.
