### ISSUE TITLE
Process with V8 dotnet crashes randomly

### ISSUE THREAD

**Issue by Alexandr-Ilyin** [rjamesnw/v8dotnet#25]
My scenario is I creae V8Engine evaluate some js, then disponse V8.
All is fine but periodically process crashes with:

Test host process crashed : #
Fatal error in C:\ProgramData\Google\V8\src\v8\src/api-inl.h, line 126
Debug check failed: allow_empty_handle || that != nullptr.####FailureMessage Object: 000000637837EBF0#
Fatal error in ../../src/base/platform/mutex.cc, line 207

Debug check failed: 0 == level_ (0 vs. 1).####FailureMessage Object: 000000637C1F90E0==== C stack trace ===============================	(No symbol) [0x00007FF892A541EB]	(No symbol) [0x00007FF89276F921]	(No symbol) [0x00007FF89276090F]	(No symbol) [0x00007FF89275F6B3]	(No symbol) [0x00007FF892766574]	(No symbol) [0x00007FF891EA8923]	(No symbol) [0x00007FF891EAE4EE]	(No symbol) [0x00007FF8918162DB]	(No symbol) [0x00007FF8917F986A]==== C stack trace ===============================		DestroyV8EngineProxy [0xDestroyV8EngineProxy [0x00007FF8917FC4CD+109]00007FF892A541EB+19220107]	V8ExecuteCompiledScript [0x00007FF89276F921+16186817]		(No symbol) [0xV8ExecuteCompiledScript [0x00007FF89276090F+16125359]	V8ExecuteCompiledScript [0x00007FF89275F6B3+16120659]	V8ExecuteCompiledScript [0x00007FF891835DD6+221814]00007FF8406EAFFE]	(No symbol) [0x00007FF8917F9213]	DisposeHandleProxy [0x00007FF8917FC5DC+236]	(No symbol) [0x00007FF8406DDE3E]

I've tried to make minimal test, but no luck so far

**Comment by rjamesnw** [comment]
First thing: Make sure you have the updated version, as the issue may already be fixed.

It could be for any number of reasons.  I would need to recreate the issue, as it works for me - but of course, your scenario may be different.   I would need either the project you are working on, or a small project that encapsulates the gist of what you are trying to do that reproduces the issue.

You could also consider not disposing V8.Net.   The latest version of V8.Net supports creating a new execution context.  Just create a new context, swap out the old for the new, and dispose the old one. That may be safer, in case there are call-backs you have set up trying to do stuff.  I believe handles are safe across contexts, but not engine instances, which can also cause errors.

**Comment by Alexandr-Ilyin** [comment]
Hello, 
Thank you for your answer. Still can not reproduce the issue in tests, I do not use callbacks or some complex stuff, I do following:
```

using (_v8Engine = new V8Engine { DefaultMemberBindingSecurity = ScriptMemberSecurity.ReadWrite })
     _v8Engine.LoadScript("...");
     _v8Engine.GlobalObject.SetProperty("myVar", _v8Engine.CreateValue("Value"));
     _v8Engine.RegisterType<ResultContainer>(null, true);

     using (InternalHandle resultHandle = _v8Engine.Execute("Some script....", null)) {
              return resultHandleValue.Value;
     }
}
public class ResultContainer
{
  public ResultContainer(string value)
  {
     Value = value;
   }
   public string Value { get; set; }
}

```                
May be you can guess, what could be a weak point here.
Or may be suggest how Context should be used there ?

**Comment by rjamesnw** [comment]
The first `using` statement is missing a brace for the scope. The engine will be disposed before the rest of the lines execute. Make sure the engine doesn’t get disposed too soon.
