### ISSUE TITLE
Support for decimal type

### ISSUE THREAD

**Issue by strattonlead** [rjamesnw/v8dotnet#34]
Hi I have an issue,

I did some tests on calculation and formatting and came over the issue, where you register an object with decimal and double properties. For doubles everything works just fine, but decimal is not known. It always gets converted to object [object Decimal].

I know the calculation of decimal and double are different in C# as well, but there might be a solution as for example treating decimals as doubles inside the engine?

**Comment by rjamesnw** [comment]
V8.Net is just a wrapper only, and originally didn't do much more than that, but there was some code added to provided basic functionality to auto-wrap types and objects. There is no way to represent `decimal` in JavaScript like you can with `double`.  Your best option is to call an `IConvertible` method on that object from JavaScript to convert to a local number (may have precision loss of course), or expose the decimal as a string, and send the string to the JS environment and handle it yourself using a 3rd-party library for large decimal numbers.

**Comment by strattonlead** [comment]
Work's perfectly as you described it. Converting decimal to double and back. We just add some container classes.
