### ISSUE TITLE
crash with WriteLine(Object.getPrototypeOf('foo'))

### ISSUE THREAD

**Issue by vvuk** [rjamesnw/v8dotnet#4]
(development branch)

This causes a native crash in v8, with the stack trace below.. not sure if this is a v8 bug or a v8.net bug.  Can be reproduced by running the Console.exe tool and evaluating:

```Console.WriteLine(Object.getPrototype('foo'))```

(note the bogus quotes around 'foo')

v8 version is whatever the hash is in the download script

**Comment by rjamesnw** [comment]
That's because for the console test I dumped many CLR types at the root level.  That means `Object` is set by this line:
`_JSServer.RegisterType(typeof(Object), "Object", true, ScriptMemberSecurity.Locked);`
So your statement won't work until you comment out that line. ;)

**Comment by rjamesnw** [comment]
Also, you have an error - the function name is not correct, perhaps should be `Object.getPrototypeOf()`.
