### ISSUE TITLE
Does V8.NET require node installed?

### ISSUE THREAD

**Issue by atotalnoob** [rjamesnw/v8dotnet#8]
Are there any dependencies outside of .NET framework/.NET Standard?

Is node or V8 installation required?

**Comment by rjamesnw** [comment]
Node is not required. V8 is statically linked with the proxy C++ library.

**Comment by atotalnoob** [comment]
Is chrome required to be installed?

**Comment by rjamesnw** [comment]
Nope, just the V8 source only.  Run `Source/V8.NET-Proxy/V8/V8Update.cmd`, and see the `ReadMe.txt` that is with it.

**Comment by rjamesnw** [comment]
V8.Net existed YEARS before any V8 NuGet package was available.  It is not built using NuGet. Perhaps one day I will, but I like having complete control over every aspect of the process. ;)
