### ISSUE TITLE
do v8.net can excute script code by function name after loaded javascript file.

### ISSUE THREAD

**Issue by drearyrainDeng** [rjamesnw/v8dotnet#9]
Hi,do v8.net suppurt that excute a function by name after loaded  javascript files.  like it:

![image](https://user-images.githubusercontent.com/35326823/55772046-25bd6a00-5abd-11e9-9411-37c3c173e633.png)

![image](https://user-images.githubusercontent.com/35326823/55772245-03781c00-5abe-11e9-99c5-0baf5994f6d1.png)

In fact, i want "Invoke" function  as same as ClearScript !  any plan?

**Comment by drearyrainDeng** [comment]
![image](https://user-images.githubusercontent.com/35326823/55772853-bc3f5a80-5ac0-11e9-84a6-96d19c4bd90d.png)

it is good if v8.net implement it .

**Comment by rjamesnw** [comment]
I don't need to implement it.  V8.Net supports DLR (Dynamic Language Runtime), so you can simply do this: `v8Engine.DynamicGlobalObject.funa();`.  In fact, you can simply cast any handle to `dynamic` to work with objects and functions in JavaScript.  The `DynamicGlobalObject` property does exactly that: `public dynamic DynamicGlobalObject { get { return GlobalObject; } }`

**Comment by drearyrainDeng** [comment]
thank for you reply .   the quesion is that function name is from xml file as a var ,so i can not code it in source like  "globalScope.funa();"  ! in this case , how can i implement it? thank you again!

**Comment by rjamesnw** [comment]
Sorry, I don’t understand what you want to do. You asked me how to invoke it and I explained how to. Now you’re asking me about some XML file without any details to go on. Please be more specific, thanks. ;) (perhaps some examples)

**Comment by drearyrainDeng** [comment]
sorry,let me clarify.
e.g. 
xlm file  just a line like that
"<node   scriptFile="test.js"  functionName="hello"   params="arg1,arg2"/>"

step:
a. read xml file to get scriptfilename、functionname and params
b.load script to v8.net by scriptfilename.
c. execute script (just the part what i set by functionName)

if any question,please let me know!

**Comment by rjamesnw** [comment]
Ah ok, I see what you mean.  For now you have to use `v8Engine.Execute()` and create the call yourself, which is easy:

    var result = v8Engine.Execute(funcname + $"({p1}, '{p2}')");

I'll look into doing something easier for the next release.

**Comment by rjamesnw** [comment]
I forgot to mention that the handle has a `.Call()` method, have you tried that?  It is good to review all handole methods, since most actions occur against a handle returned from V8 and not the engine.  If you need to pass in a parameter from C# just use `V8Engine,CreateValue()`, or similar.

    v8Engine.GlobalObject.Call("funca", InternalHandle.Empty, Engine.CreateValue(123))

**Comment by drearyrainDeng** [comment]
waoo! very well. it work normal, thank a lot.  i miss it
